package api

// REST API models - non-generated versions of types that were previously
// generated by gqlgen. These types are used by REST handlers and maintain
// the same JSON serialization format for backward compatibility.
//
// Types from pkg/models are used directly when possible.
// Types in generated_models.go that are still needed are imported from there
// until the generated_models.go file is removed (Stage 9).
//
// NOTE: During the migration, both REST and GraphQL coexist.
// The types in generated_models.go continue to be used by GraphQL resolvers.
// REST handlers can use the same types since they have proper json tags.
