// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package loaders

import (
	"sync"
	"time"
)

// SceneOHistoryLoaderConfig captures the config to create a new SceneOHistoryLoader
type SceneOHistoryLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []int) ([]TimeSlice, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewSceneOHistoryLoader creates a new SceneOHistoryLoader given a fetch, wait, and maxBatch
func NewSceneOHistoryLoader(config SceneOHistoryLoaderConfig) *SceneOHistoryLoader {
	return &SceneOHistoryLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// SceneOHistoryLoader batches and caches requests
type SceneOHistoryLoader struct {
	// this method provides the data for the loader
	fetch func(keys []int) ([]TimeSlice, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[int]TimeSlice

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *sceneOHistoryLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type sceneOHistoryLoaderBatch struct {
	keys    []int
	data    []TimeSlice
	error   []error
	closing bool
	done    chan struct{}
}

// Load a TimeSlice by key, batching and caching will be applied automatically
func (l *SceneOHistoryLoader) Load(key int) (TimeSlice, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a TimeSlice.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *SceneOHistoryLoader) LoadThunk(key int) func() (TimeSlice, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (TimeSlice, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &sceneOHistoryLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (TimeSlice, error) {
		<-batch.done

		var data TimeSlice
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *SceneOHistoryLoader) LoadAll(keys []int) ([]TimeSlice, []error) {
	results := make([]func() (TimeSlice, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	timeSlices := make([]TimeSlice, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		timeSlices[i], errors[i] = thunk()
	}
	return timeSlices, errors
}

// LoadAllThunk returns a function that when called will block waiting for a TimeSlices.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *SceneOHistoryLoader) LoadAllThunk(keys []int) func() ([]TimeSlice, []error) {
	results := make([]func() (TimeSlice, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]TimeSlice, []error) {
		timeSlices := make([]TimeSlice, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			timeSlices[i], errors[i] = thunk()
		}
		return timeSlices, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *SceneOHistoryLoader) Prime(key int, value TimeSlice) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		l.unsafeSet(key, value)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *SceneOHistoryLoader) Clear(key int) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *SceneOHistoryLoader) unsafeSet(key int, value TimeSlice) {
	if l.cache == nil {
		l.cache = map[int]TimeSlice{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *sceneOHistoryLoaderBatch) keyIndex(l *SceneOHistoryLoader, key int) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *sceneOHistoryLoaderBatch) startTimer(l *SceneOHistoryLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *sceneOHistoryLoaderBatch) end(l *SceneOHistoryLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
