// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ColorPresetReaderWriter is an autogenerated mock type for the ColorPresetReaderWriter type
type ColorPresetReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, newColorPreset
func (_m *ColorPresetReaderWriter) Create(ctx context.Context, newColorPreset models.ColorPreset) (*models.ColorPreset, error) {
	ret := _m.Called(ctx, newColorPreset)

	var r0 *models.ColorPreset
	if rf, ok := ret.Get(0).(func(context.Context, models.ColorPreset) *models.ColorPreset); ok {
		r0 = rf(ctx, newColorPreset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ColorPreset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.ColorPreset) error); ok {
		r1 = rf(ctx, newColorPreset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *ColorPresetReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *ColorPresetReaderWriter) Find(ctx context.Context, id int) (*models.ColorPreset, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.ColorPreset
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.ColorPreset); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ColorPreset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *ColorPresetReaderWriter) FindAll(ctx context.Context) ([]*models.ColorPreset, error) {
	ret := _m.Called(ctx)

	var r0 []*models.ColorPreset
	if rf, ok := ret.Get(0).(func(context.Context) []*models.ColorPreset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ColorPreset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, updatedColorPreset
func (_m *ColorPresetReaderWriter) Update(ctx context.Context, id int, updatedColorPreset models.ColorPresetPartial) (*models.ColorPreset, error) {
	ret := _m.Called(ctx, id, updatedColorPreset)

	var r0 *models.ColorPreset
	if rf, ok := ret.Get(0).(func(context.Context, int, models.ColorPresetPartial) *models.ColorPreset); ok {
		r0 = rf(ctx, id, updatedColorPreset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ColorPreset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, models.ColorPresetPartial) error); ok {
		r1 = rf(ctx, id, updatedColorPreset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
