// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GameReaderWriter is an autogenerated mock type for the GameReaderWriter type
type GameReaderWriter struct {
	mock.Mock
}

// AddO provides a mock function with given fields: ctx, id, dates
func (_m *GameReaderWriter) AddO(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddOMG provides a mock function with given fields: ctx, id, dates
func (_m *GameReaderWriter) AddOMG(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddViews provides a mock function with given fields: ctx, sceneID, dates
func (_m *GameReaderWriter) AddViews(ctx context.Context, sceneID int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, sceneID, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, sceneID, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, sceneID, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// All provides a mock function with given fields: ctx
func (_m *GameReaderWriter) All(ctx context.Context) ([]*models.Game, error) {
	ret := _m.Called(ctx)

	var r0 []*models.Game
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Game); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountViews provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) CountViews(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, game
func (_m *GameReaderWriter) Create(ctx context.Context, game *models.Game) error {
	ret := _m.Called(ctx, game)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Game) error); ok {
		r0 = rf(ctx, game)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrementOCounter provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) DecrementOCounter(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecrementOMGCounter provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) DecrementOMGCounter(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAllViews provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) DeleteAllViews(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteO provides a mock function with given fields: ctx, id, dates
func (_m *GameReaderWriter) DeleteO(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOMG provides a mock function with given fields: ctx, id, dates
func (_m *GameReaderWriter) DeleteOMG(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteViews provides a mock function with given fields: ctx, id, dates
func (_m *GameReaderWriter) DeleteViews(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) Find(ctx context.Context, id int) (*models.Game, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Game
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ctx, ids
func (_m *GameReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Game, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*models.Game
	if rf, ok := ret.Get(0).(func(context.Context, []int) []*models.Game); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyOCount provides a mock function with given fields: ctx, ids
func (_m *GameReaderWriter) GetManyOCount(ctx context.Context, ids []int) ([]int, error) {
	ret := _m.Called(ctx, ids)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, []int) []int); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyODates provides a mock function with given fields: ctx, ids
func (_m *GameReaderWriter) GetManyODates(ctx context.Context, ids []int) ([][]time.Time, error) {
	ret := _m.Called(ctx, ids)

	var r0 [][]time.Time
	if rf, ok := ret.Get(0).(func(context.Context, []int) [][]time.Time); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyOMGCount provides a mock function with given fields: ctx, ids
func (_m *GameReaderWriter) GetManyOMGCount(ctx context.Context, ids []int) ([]int, error) {
	ret := _m.Called(ctx, ids)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, []int) []int); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyOMGDates provides a mock function with given fields: ctx, ids
func (_m *GameReaderWriter) GetManyOMGDates(ctx context.Context, ids []int) ([][]time.Time, error) {
	ret := _m.Called(ctx, ids)

	var r0 [][]time.Time
	if rf, ok := ret.Get(0).(func(context.Context, []int) [][]time.Time); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyViewCount provides a mock function with given fields: ctx, ids
func (_m *GameReaderWriter) GetManyViewCount(ctx context.Context, ids []int) ([]int, error) {
	ret := _m.Called(ctx, ids)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, []int) []int); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyViewDates provides a mock function with given fields: ctx, ids
func (_m *GameReaderWriter) GetManyViewDates(ctx context.Context, ids []int) ([][]time.Time, error) {
	ret := _m.Called(ctx, ids)

	var r0 [][]time.Time
	if rf, ok := ret.Get(0).(func(context.Context, []int) [][]time.Time); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetODates provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) GetODates(ctx context.Context, id int) ([]time.Time, error) {
	ret := _m.Called(ctx, id)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int) []time.Time); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOMGDates provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) GetOMGDates(ctx context.Context, id int) ([]time.Time, error) {
	ret := _m.Called(ctx, id)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int) []time.Time); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetViewDates provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) GetViewDates(ctx context.Context, id int) ([]time.Time, error) {
	ret := _m.Called(ctx, id)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int) []time.Time); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImage provides a mock function with given fields: ctx, gameID
func (_m *GameReaderWriter) GetImage(ctx context.Context, gameID int) ([]byte, error) {
	ret := _m.Called(ctx, gameID)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, int) []byte); ok {
		r0 = rf(ctx, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementOCounter provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) IncrementOCounter(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementOMGCounter provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) IncrementOMGCounter(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: ctx, gameFilter, findFilter
func (_m *GameReaderWriter) Query(ctx context.Context, gameFilter *models.GameFilterType, findFilter *models.FindFilterType) ([]*models.Game, int, error) {
	ret := _m.Called(ctx, gameFilter, findFilter)

	var r0 []*models.Game
	if rf, ok := ret.Get(0).(func(context.Context, *models.GameFilterType, *models.FindFilterType) []*models.Game); ok {
		r0 = rf(ctx, gameFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Game)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *models.GameFilterType, *models.FindFilterType) int); ok {
		r1 = rf(ctx, gameFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *models.GameFilterType, *models.FindFilterType) error); ok {
		r2 = rf(ctx, gameFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// QueryCount provides a mock function with given fields: ctx, gameFilter, findFilter
func (_m *GameReaderWriter) QueryCount(ctx context.Context, gameFilter *models.GameFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _m.Called(ctx, gameFilter, findFilter)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *models.GameFilterType, *models.FindFilterType) int); ok {
		r0 = rf(ctx, gameFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.GameFilterType, *models.FindFilterType) error); ok {
		r1 = rf(ctx, gameFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetO provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) ResetO(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetOCounter provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) ResetOCounter(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetOMG provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) ResetOMG(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetOMGCounter provides a mock function with given fields: ctx, id
func (_m *GameReaderWriter) ResetOMGCounter(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, game
func (_m *GameReaderWriter) Update(ctx context.Context, game *models.Game) error {
	ret := _m.Called(ctx, game)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Game) error); ok {
		r0 = rf(ctx, game)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePartial provides a mock function with given fields: ctx, id, partial
func (_m *GameReaderWriter) UpdatePartial(ctx context.Context, id int, partial models.GamePartial) (*models.Game, error) {
	ret := _m.Called(ctx, id, partial)

	var r0 *models.Game
	if rf, ok := ret.Get(0).(func(context.Context, int, models.GamePartial) *models.Game); ok {
		r0 = rf(ctx, id, partial)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, models.GamePartial) error); ok {
		r1 = rf(ctx, id, partial)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTagIDs provides a mock function with given fields: ctx, relatedID
func (_m *GameReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _m.Called(ctx, relatedID)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = rf(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasImage provides a mock function with given fields: ctx, gameID
func (_m *GameReaderWriter) HasImage(ctx context.Context, gameID int) (bool, error) {
	ret := _m.Called(ctx, gameID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, gameID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetURLs provides a mock function with given fields: ctx, relatedID
func (_m *GameReaderWriter) GetURLs(ctx context.Context, relatedID int) ([]string, error) {
	ret := _m.Called(ctx, relatedID)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
