// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// PerformerProfileImageReaderWriter is an autogenerated mock type for the PerformerProfileImageReaderWriter type
type PerformerProfileImageReaderWriter struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *PerformerProfileImageReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, newImage
func (_m *PerformerProfileImageReaderWriter) Create(ctx context.Context, newImage *models.CreatePerformerProfileImageInput) (*models.PerformerProfileImage, error) {
	ret := _m.Called(ctx, newImage)

	var r0 *models.PerformerProfileImage
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreatePerformerProfileImageInput) *models.PerformerProfileImage); ok {
		r0 = rf(ctx, newImage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PerformerProfileImage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.CreatePerformerProfileImageInput) error); ok {
		r1 = rf(ctx, newImage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *PerformerProfileImageReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *PerformerProfileImageReaderWriter) Find(ctx context.Context, id int) (*models.PerformerProfileImage, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.PerformerProfileImage
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.PerformerProfileImage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PerformerProfileImage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPerformerID provides a mock function with given fields: ctx, performerID
func (_m *PerformerProfileImageReaderWriter) FindByPerformerID(ctx context.Context, performerID int) ([]*models.PerformerProfileImage, error) {
	ret := _m.Called(ctx, performerID)

	var r0 []*models.PerformerProfileImage
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.PerformerProfileImage); ok {
		r0 = rf(ctx, performerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PerformerProfileImage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, performerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImage provides a mock function with given fields: ctx, id
func (_m *PerformerProfileImageReaderWriter) GetImage(ctx context.Context, id int) ([]byte, error) {
	ret := _m.Called(ctx, id)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, int) []byte); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasImage provides a mock function with given fields: ctx, id
func (_m *PerformerProfileImageReaderWriter) HasImage(ctx context.Context, id int) (bool, error) {
	ret := _m.Called(ctx, id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateImage provides a mock function with given fields: ctx, id, image
func (_m *PerformerProfileImageReaderWriter) UpdateImage(ctx context.Context, id int, image []byte) error {
	ret := _m.Called(ctx, id, image)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []byte) error); ok {
		r0 = rf(ctx, id, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePartial provides a mock function with given fields: ctx, id, updatedImage
func (_m *PerformerProfileImageReaderWriter) UpdatePartial(ctx context.Context, id int, updatedImage models.PerformerProfileImagePartial) (*models.PerformerProfileImage, error) {
	ret := _m.Called(ctx, id, updatedImage)

	var r0 *models.PerformerProfileImage
	if rf, ok := ret.Get(0).(func(context.Context, int, models.PerformerProfileImagePartial) *models.PerformerProfileImage); ok {
		r0 = rf(ctx, id, updatedImage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PerformerProfileImage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, models.PerformerProfileImagePartial) error); ok {
		r1 = rf(ctx, id, updatedImage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
