// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// SceneSimilarityReaderWriter is an autogenerated mock type for the SceneSimilarityReaderWriter type
type SceneSimilarityReaderWriter struct {
	mock.Mock
}

// CleanupOrphanedSimilarities provides a mock function with given fields: ctx
func (_m *SceneSimilarityReaderWriter) CleanupOrphanedSimilarities(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with given fields: ctx
func (_m *SceneSimilarityReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, newObject
func (_m *SceneSimilarityReaderWriter) Create(ctx context.Context, newObject models.SceneSimilarity) (*models.SceneSimilarity, error) {
	ret := _m.Called(ctx, newObject)

	var r0 *models.SceneSimilarity
	if rf, ok := ret.Get(0).(func(context.Context, models.SceneSimilarity) *models.SceneSimilarity); ok {
		r0 = rf(ctx, newObject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SceneSimilarity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.SceneSimilarity) error); ok {
		r1 = rf(ctx, newObject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByScene provides a mock function with given fields: ctx, sceneID
func (_m *SceneSimilarityReaderWriter) DeleteByScene(ctx context.Context, sceneID int) error {
	ret := _m.Called(ctx, sceneID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, sceneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBySceneAsSource provides a mock function with given fields: ctx, sceneID
func (_m *SceneSimilarityReaderWriter) DeleteBySceneAsSource(ctx context.Context, sceneID int) error {
	ret := _m.Called(ctx, sceneID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, sceneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *SceneSimilarityReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *SceneSimilarityReaderWriter) Find(ctx context.Context, id int) (*models.SceneSimilarity, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.SceneSimilarity
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.SceneSimilarity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SceneSimilarity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByScenePair provides a mock function with given fields: ctx, sceneID, similarSceneID
func (_m *SceneSimilarityReaderWriter) FindByScenePair(ctx context.Context, sceneID int, similarSceneID int) (*models.SceneSimilarity, error) {
	ret := _m.Called(ctx, sceneID, similarSceneID)

	var r0 *models.SceneSimilarity
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.SceneSimilarity); ok {
		r0 = rf(ctx, sceneID, similarSceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SceneSimilarity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, sceneID, similarSceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSimilarScenes provides a mock function with given fields: ctx, sceneID, limit
func (_m *SceneSimilarityReaderWriter) FindSimilarScenes(ctx context.Context, sceneID int, limit int) ([]*models.SceneSimilarity, error) {
	ret := _m.Called(ctx, sceneID, limit)

	var r0 []*models.SceneSimilarity
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.SceneSimilarity); ok {
		r0 = rf(ctx, sceneID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SceneSimilarity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, sceneID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, updatedObject
func (_m *SceneSimilarityReaderWriter) Update(ctx context.Context, updatedObject models.SceneSimilarity) (*models.SceneSimilarity, error) {
	ret := _m.Called(ctx, updatedObject)

	var r0 *models.SceneSimilarity
	if rf, ok := ret.Get(0).(func(context.Context, models.SceneSimilarity) *models.SceneSimilarity); ok {
		r0 = rf(ctx, updatedObject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SceneSimilarity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.SceneSimilarity) error); ok {
		r1 = rf(ctx, updatedObject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, similarity
func (_m *SceneSimilarityReaderWriter) Upsert(ctx context.Context, similarity models.SceneSimilarity) error {
	ret := _m.Called(ctx, similarity)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SceneSimilarity) error); ok {
		r0 = rf(ctx, similarity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
